from building import *
import os

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = ['data_config.c','tencent_cloud.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
